name: hi
description: An eco-friendly task management app for kids
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  flutter_screenutil: ^5.9.0
  auto_size_text: ^3.0.0

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # State Management & UI
  provider: ^6.1.1
  lottie: ^2.7.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  webview_flutter: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
